ar-io/arns-service

- src/constants.ts
- src/router.ts
- src/routes/contract.ts
- src/routes/prometheus.ts
- src/routes/swagger.ts
- src/routes/wallet.ts
In koa, the use of `next()` allows for async middleware. It is not necessary, and actually creates unexpected behavior to use `return next()` within route handlers as it passes control flow to the next route that matches the request path, rather then returning the response. Going forward, `next()` is likely only needed in middlware, unless we have some special path chaining we are trying to do.
> chore(refactor): remove `return next()` from router handlers

- src/api/warp.ts
- src/middleware/warp.ts
Some read interactions are failing, and right now we assume the input is incorrect. This modifies the response/error to include the read interaction error messaging, and throw either an `EvaluationError` or `UnknownError` depending on what the response from `viewState()` returns.
Also breaks apart `stateRequestMap` and `readRequestMap` into separate objects with proper types from `Warp`, to make it easier to debug our caching.
Example response:
```
❯ curl -iL http://localhost:3000/v1/contract/fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ/read/priceForInteraction\?interactionName\=buyRecord\&name\=new-name-10\&years\=1\&type\=lease\&contractTxId\=atomic
HTTP/1.1 400 Bad Request
Vary: Origin
Access-Control-Allow-Origin: 
Content-Type: text/plain; charset=utf-8
Content-Length: 43
Date: Mon, 20 …
```
> fix(read): return read interaction errors if they fail

- src/constants.ts
- src/router.ts
We were using a regex to prevent arbitaray requests creating potential issues in the service. Given the expanding set of fields, and the desire to support ant contracts that may have extended schemas, we can remove this regex in the service. If the field does not exist on the state, a 404 will be returned.
> fix(regex): remove field regex for contract fields

- src/middleware/warp.ts
This may be causing issues with lmdb. Ensuring lmdb does not use `noSync` which does not flush state to disk and is enabled by default with `defaultCacheOptions`.
Docs: https://github.com/kriszyp/lmdb-js#lmdb-flags
Ticket: [PE-5072](https://ardrive.atlassian.net/browse/PE-5072)
[PE-5072]: https://ardrive.atlassian.net/browse/PE-5072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(warp): do not use in memory lmdb cache

- package.json
- src/middleware/warp.ts
- yarn.lock
Were seeing state corruption in lmdb implementation. An issue was created with warp-contracts-lmdb, but for now we will migrate to sqlite.
Related: https://github.com/warp-contracts/warp-contracts-lmdb/issues/26
Example log:
```
cacheKey":"fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ-priceForInteraction-dbf5a69f55ab199c955d1c4df17aaf990435ea2b65e17c5aaa08af851b6dea27-7be80150a81463abc033a504e0ba48cd4ea8f93bdecb29b3e0d096ed09268237","contractTxId":"fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ","errorMessage":"Error: Database is not open\n    at maybeOpened (/usr/src/app/node_modules/abstract-level/abstract-level.js:133:18)\n    at /usr/src/app/node_modules/abstract-level/abstract-level.js:160:13\n    at process.processTicksAndRejections …
```
> feat(sqlite): move from warp-contracts-lmdb to warp-contracts-sqlite

- src/api/warp.ts
We are using very little memory (<10% on average) and this will avoid thrashing of the cache when various requets come in.
> chore(cache): bump read through promise cache capacity

- src/constants.ts
…o true
This may help avoid issues when evaluating contracts with expensive interactions that do not have a contract-manifest set
> fix(warp): set default evaluation timeout to one hour

- src/middleware/warp.ts
This should have been already set, it may be causing the memory issues we saw in the service.
> fix(warp): set `inMemory` to `false` for sqlite database

- src/middleware/arweave.ts
We are seeing issues when evaluating against ar-io.dev. We will switch to arweave.net while those get sorted.
> fix(warp): use `arweave.net` for state evaluation

- src/api/graphql.ts
- src/types.ts
- tests/integration/routes.test.ts
We already fetch the height, so easy enough to add the timestamp
> feat(warp): add block timestamp to interactions endpoint

- src/api/graphql.ts
This will throw out any poorly formatted tags when fetching interactions from gql.
> fix(gql): validate tags for gql interactions

- src/api/graphql.ts
- src/types.ts
- tests/integration/routes.test.ts
New interactions example:
```json
{
"height": 1311127,
"timestamp": 1701123593,
"sortKey": "000001311127,0000000000000,dde3bb75a7b976d2e627e65ba77eaa51d3d4ea80ede4785d2984d38b558f3a9c",
"input": {
"function": "buyRecord",
"name": "zekkava0",
"contractTxId": "atomic",
"type": "lease",
"years": 1,
"auction": false
},
"owner": "2sbEg15TKqH-GH1yyxsnBAshlfSK0lRqtMNq4Jrp4OI",
"valid": true,
"id": "wsbJ-O075SObUe78Eqf0Q2563rWso6evjL4JjrjO3Y4"
},
```
> feat(gql): add `sortKey` and validate interactions from GQL

- src/api/graphql.ts
- src/routes/contract.ts
- src/types.ts
Mapping times after the retrievals seems to be somewhat non-performant based on log outputs. We should investigate further. Example logs:
```
debug: Fetching contract interactions {"contractTxId":"-8A6RexFkpfWwuyVO98wzSFZh0d6VJuI-buTJvlwOJQ","method":"GET","path":"/v1/contract/-8A6RexFkpfWwuyVO98wzSFZh0d6VJuI-buTJvlwOJQ/interactions","timestamp":"2023-12-10T18:03:11.187Z","trace":"387b2d"}
debug: Mapping interactions {"contractTxId":"-8A6RexFkpfWwuyVO98wzSFZh0d6VJuI-buTJvlwOJQ","method":"GET","path":"/v1/contract/-8A6RexFkpfWwuyVO98wzSFZh0d6VJuI-buTJvlwOJQ/interactions","timestamp":"2023-12-10T18:03:11.187Z","trace":"387b2d"}
debug: Setting cache-control to max-age=30. {"method":"GET","path":"/v1/contract/-8A6RexFkpfWwuyVO98wzSFZh0d6VJuI-buTJvlwOJQ/interactions","timestamp":"2023-12-10T18: …
```
> PE-5202: add a readthroughpromisecache for contract interactions 

- src/api/graphql.ts
The same cache key is being set for varying blockheights, causing the read through cache to return incorrect interactions when a new request with a different blockHeight is created before the cache has expired.
CC @arielmelendez 
```bash
Reading through to wallet interactions for contract... {"blockHeightFilter":1321450,"cacheKey":"bLAgYxAdX2Ry-nt6aH2ixgvJXbpsEYm28NgJgyqfs-U-this.blockHeight","contractTxId":"bLAgYxAdX2Ry-nt6aH2ixgvJXbpsEYm28NgJgyqfs-U","method":"GET","path":"/v1/contract/bLAgYxAdX2Ry-nt6aH2ixgvJXbpsEYm28NgJgyqfs-U/interactions","timestamp":"2023-12-13T08:48:13.463Z","trace":"ecd1e3"}
```
Specifically: `"cacheKey":"bLAgYxAdX2Ry-nt6aH2ixgvJXbpsEYm28NgJgyqfs-U-this.blockHeight"`
```bash
Reading through to wallet interactions for contract... …
```
> fix(gql): fix cacheKey construction for gql interactions

- package.json
- src/api/graphql.ts
- src/api/warp.ts
- src/constants.ts
- src/errors.ts
- src/middleware/errors.ts
- src/routes/contract.ts
- src/routes/wallet.ts
- yarn.lock
This update allows us to pass abort signals to warp evaluation and sets a default timeout of 2 mins for state evaluation. Includes updates to our read-through promises to support AbortSignals so we do not continue doing work once the response is returned to the client.
> feat(warp): bump warp to use evaluation timeout abort controllers

- src/app.ts
- src/config.ts
- src/middleware/warp.ts
- src/routes/contract.ts
- src/system.ts
This should help alleviate pain after new deploys, and hydrate caches for contracts that have a lot of interactions as early as possible.
There's more we can do on the deploy side to check the status of these contracts before opening the tasks up for requests.
> feat(prefetch): prefetch contract states on startup

- src/api/graphql.ts
Older ANTs were being dropped when processing contracts.
> fix(PE-5012): fix gql query for fetching contracts

- .gitignore
- package.json
- src/app.ts
- src/constants.ts
- src/middleware/warp.ts
- src/system.ts
- yarn.lock
This speeds up the time to load various contracts, we will later add updating the cache on shutdown or something similar.
Logs:
```bash
{"level":"info","message":"Bootstrapping warp cache from S3","params":{"Bucket":"arns-warp-cache","Key":"cache"},"timestamp":"2024-01-17T01:09:08.598Z"}
{"keepAliveTimeout":180000,"level":"info","message":"Server is listening...","port":3000,"requestTimeout":180000,"timestamp":"2024-01-17T01:09:08.604Z"}
{"durationMs":8367,"level":"info","message":"Successfully bootstrapped warp cache from S3","timestamp":"2024-01-17T01:09:16.961Z"}
{"contractTxIds":["bLAgYxAdX2Ry-nt6aH2ixgvJXbpsEYm28NgJgyqfs-U","fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ"],"level":"info","message":"Pre-fetching contracts...","timestamp":"2024-01-17T01:09:16.962Z"} …
```
> feat(s3): bootstrap the cache from S3 

- docs/openapi.yaml
- src/middleware/query.ts
- src/routes/contract.ts
- tests/integration/arlocal/index.js
- tests/integration/routes.test.ts
Example: 
```
❯ curl -s http://localhost:3000/v1/contract/bLAgYxAdX2Ry-nt6aH2ixgvJXbpsEYm28NgJgyqfs-U/interactions\?function\=joinNetwork\&pageSize\=2 | jq '.'
{
"contractTxId": "bLAgYxAdX2Ry-nt6aH2ixgvJXbpsEYm28NgJgyqfs-U",
"sortKey": "000001384313,0000000000000,c32b0e886cca125d6503c9509eab071a751c1ba05a63070068908a64cbd30e20",
"interactions": [
{
"height": 1384303,
"timestamp": 1710549800,
"input": {
"function": "joinNetwork",
"observerWallet": "Zwh1vYmwfbESP9-rXVXiNS8Ix0MEsUw5GSiObwkVEDE",
"qty": 10000,
"label": "KhangNguyenVNB",
"fqdn": "khang.pro",
"port": 443,
"protocol": "https",
"properties": "FH1aVetOoulPGqgYukj0VE0wIhDy90WiQoV3U2PeY44",
"note": "Khang Nguyen from VNBnode (VietNam community) https://t.me/VNBnodegroup 😁"
},
"owner": "Zwh1vYmwfbESP9-rXVXiNS8Ix0MEsUw5GSiObwkVEDE", …
```
> feat(interactions): allow filtering interactions by function name

- src/api/warp.ts
- src/constants.ts
Error:
```
(node:1) TimeoutOverflowWarning: 9007199254740991000 does not fit into a 32-bit signed integer.
```
> fix(eval): limit evaluation time to 32-bit integer not nodejs max
